-- Direct SQL to add all missing columns to SpareParts table
-- Run this directly in SQL Server Management Studio

USE ServiceCrm;
GO

-- Check current table structure
PRINT '=== Current SpareParts Table Structure ===';
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'SpareParts'
ORDER BY ORDINAL_POSITION;
GO

PRINT '';
PRINT '=== Adding Missing Columns ===';

-- Add DESCRIPTION if missing
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SpareParts' AND COLUMN_NAME = 'DESCRIPTION')
BEGIN
    ALTER TABLE [SpareParts] ADD [DESCRIPTION] VARCHAR(255) NULL;
    PRINT '✓ Added DESCRIPTION column';
END
ELSE
BEGIN
    PRINT '• DESCRIPTION column already exists';
END
GO

-- Add MAPPED_MODEL if missing
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SpareParts' AND COLUMN_NAME = 'MAPPED_MODEL')
BEGIN
    ALTER TABLE [SpareParts] ADD [MAPPED_MODEL] VARCHAR(50) NULL;
    PRINT '✓ Added MAPPED_MODEL column';
END
ELSE
BEGIN
    PRINT '• MAPPED_MODEL column already exists';
END
GO

-- Add MODEL_DESCRIPTION if missing
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SpareParts' AND COLUMN_NAME = 'MODEL_DESCRIPTION')
BEGIN
    ALTER TABLE [SpareParts] ADD [MODEL_DESCRIPTION] VARCHAR(255) NULL;
    PRINT '✓ Added MODEL_DESCRIPTION column';
END
ELSE
BEGIN
    PRINT '• MODEL_DESCRIPTION column already exists';
END
GO

-- Add MAX_USED_QTY if missing
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SpareParts' AND COLUMN_NAME = 'MAX_USED_QTY')
BEGIN
    ALTER TABLE [SpareParts] ADD [MAX_USED_QTY] INT NULL;
    PRINT '✓ Added MAX_USED_QTY column';
END
ELSE
BEGIN
    PRINT '• MAX_USED_QTY column already exists';
END
GO

-- Add SERVICE_LEVEL if missing
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SpareParts' AND COLUMN_NAME = 'SERVICE_LEVEL')
BEGIN
    ALTER TABLE [SpareParts] ADD [SERVICE_LEVEL] VARCHAR(50) NULL;
    PRINT '✓ Added SERVICE_LEVEL column';
END
ELSE
BEGIN
    PRINT '• SERVICE_LEVEL column already exists';
END
GO

-- Add PART_LOCATION if missing
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SpareParts' AND COLUMN_NAME = 'PART_LOCATION')
BEGIN
    ALTER TABLE [SpareParts] ADD [PART_LOCATION] VARCHAR(100) NULL;
    PRINT '✓ Added PART_LOCATION column';
END
ELSE
BEGIN
    PRINT '• PART_LOCATION column already exists';
END
GO

-- Add STATUS if missing
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SpareParts' AND COLUMN_NAME = 'STATUS')
BEGIN
    ALTER TABLE [SpareParts] ADD [STATUS] VARCHAR(50) NULL;
    PRINT '✓ Added STATUS column';
END
ELSE
BEGIN
    PRINT '• STATUS column already exists';
END
GO

-- Add LAST_UPDATED_DATE if missing
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SpareParts' AND COLUMN_NAME = 'LAST_UPDATED_DATE')
BEGIN
    ALTER TABLE [SpareParts] ADD [LAST_UPDATED_DATE] DATETIME NULL;
    PRINT '✓ Added LAST_UPDATED_DATE column';
END
ELSE
BEGIN
    PRINT '• LAST_UPDATED_DATE column already exists';
END
GO

PRINT '';
PRINT '=== Final Table Structure ===';
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'SpareParts'
ORDER BY ORDINAL_POSITION;
GO

PRINT '';
PRINT '✅ Migration completed!';
